services:
  benchmark-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8000"
    environment:
      - POSTGRES_DB=benchmark
      - POSTGRES_USER=benchmark
      - POSTGRES_PASSWORD=benchmark
      - POSTGRES_HOST=db-python
      - POSTGRES_PORT=5432
    depends_on:
      - db-python
    mem_limit: 4g
    cpus: 3.0

  db-python:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    ports:
      - "5435:5432"
