services:
  benchmark-java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-java:5432/benchmark
      - SPRING_DATASOURCE_USERNAME=benchmark
      - SPRING_DATASOURCE_PASSWORD=benchmark
    depends_on:
      - db-java
    volumes:
      - ./results/benchmark-java:/app/results

  db-java:
    image: postgres:15
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    ports:
      - "5433:5432"
