services:
  benchmark-csharp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db-csharp;Database=benchmark;Username=benchmark;Password=benchmark
    depends_on:
      - db-csharp
    mem_limit: 4g
    cpus: 3.0

  db-csharp:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    ports:
      - "5434:5432"
