server:
  port: 8080

spring:
  application:
    name: benchmark
  datasource:
    url: jdbc:postgresql://localhost:5432/benchmark
    username: benchmark
    password: benchmark
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true