services:
    benchmark-php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8084:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db-php
            - DB_PORT=5432
            - DB_DATABASE=benchmark
            - DB_USERNAME=benchmark
            - DB_PASSWORD=benchmark
            - APP_ENV=production
            - LOG_CHANNEL=stderr
            - LOG_LEVEL=error
        depends_on:
            - db-php
        mem_limit: 4g
        cpus: 3.0

    db-php:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: benchmark
            POSTGRES_USER: benchmark
            POSTGRES_PASSWORD: benchmark
        ports:
            - "5436:5432"

